version: "3.9"

services:
  postgres:
    container_name: tipbot-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tipbot
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-tipbot}",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    restart: always

  bot:
    container_name: tipbot-bot
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/tipbot}
      LKY_RPC_URL: ${LKY_RPC_URL}
      LKY_RPC_USER: ${LKY_RPC_USER}
      LKY_RPC_PASS: ${LKY_RPC_PASS}
      MIN_CONFIRMATIONS: ${MIN_CONFIRMATIONS:-6}
      DEFAULT_DISPLAY_DECIMALS: ${DEFAULT_DISPLAY_DECIMALS:-8}
    depends_on:
      postgres:
        condition: service_healthy
    # use the actual path used in your logs:
    command: ["node", "dist/src/index.js"]
    restart: always

  worker:
    container_name: tipbot-worker
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/tipbot}
      LKY_RPC_URL: ${LKY_RPC_URL}
      LKY_RPC_USER: ${LKY_RPC_USER}
      LKY_RPC_PASS: ${LKY_RPC_PASS}
      MIN_CONFIRMATIONS: ${MIN_CONFIRMATIONS:-6}
      DEFAULT_DISPLAY_DECIMALS: ${DEFAULT_DISPLAY_DECIMALS:-8}
    depends_on:
      postgres:
        condition: service_healthy
    command: ["node", "dist/src/worker.js"]
    restart: always

volumes:
  pg: {}
