services:
  postgres:
    image: postgres:16
    container_name: tipbot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tipbot
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tipbot"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      # Logical alias → pinned to the GOOD physical volume below
      - tipbot_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro

  bot:
    build: .
    container_name: tipbot-bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    # ensure we run the npm script
    command: ["npm", "run", "start:bot"]

  worker:
    build: .
    container_name: tipbot-worker
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    # bootstrap runs first on every start, then the worker
    command: ["npm", "run", "start:worker"]

volumes:
  tipbot_data:
    external: true
    # bind the logical volume to the canonical GOOD volume on the VPS
    name: tipbotclean_pg
