services:
  postgres:
    image: postgres:16
    container_name: tipbot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tipbot
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tipbot"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - pg:/var/lib/postgresql/data
      # If ./sql contains schema .sql files, Postgres will run them automatically on *first* init of the volume
      - ./sql:/docker-entrypoint-initdb.d:ro

  bot:
    build: .
    container_name: tipbot-bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["node", "dist/src/index.js"]

  worker:
    build: .
    container_name: tipbot-worker
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["node", "dist/src/worker.js"]

volumes:
  pg: {}
