# optional: fixes project name so you don't need -p tipbotclean
name: tipbotclean

services:
  postgres:
    image: postgres:16
    container_name: tipbot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tipbot
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tipbot"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      # ✅ Adopt the existing persistent data on the VPS:
      - tipbot_data:/var/lib/postgresql/data
      # ✅ Optional schema/seed SQLs (run ONLY on first-ever empty volume init):
      - ./sql:/docker-entrypoint-initdb.d:ro

  bot:
    build: .
    container_name: tipbot-bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["node", "dist/src/index.js"]
    # (optional) tiny init so Node isn't PID 1
    init: true

  worker:
    build: .
    container_name: tipbot-worker
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["node", "dist/src/worker.js"]
    init: true

volumes:
  tipbot_data:
    external: true
    name: tipbot_data
