services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tipbot
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - tipbot_data:/var/lib/postgresql/data

  bot:
    build: .
    env_file: .env
    environment:
      LKY_RPC_URL: http://host.docker.internal:9918
      NODE_RPC_URL: http://host.docker.internal:9918
      RPC_URL: http://host.docker.internal:9918
      TZ: UTC
    depends_on: [postgres]
    init: true
    command: ["npm", "run", "start:bot"]
    extra_hosts: ["host.docker.internal:host-gateway"]

  worker:
    build: .
    env_file: .env
    environment:
      LKY_RPC_URL: http://host.docker.internal:9918
      NODE_RPC_URL: http://host.docker.internal:9918
      RPC_URL: http://host.docker.internal:9918
      TZ: UTC
    depends_on: [postgres]
    init: true
    command: ["npm", "run", "start:worker"]
    extra_hosts: ["host.docker.internal:host-gateway"]

volumes:
  tipbot_data:
    external: true
    name: tipbot_pg_sql_2025_08_31_031701
